### ISSUE TITLE
Captura de cuenta predial Ventanilla

### ISSUE THREAD

**Issue by dante02d** [GAasociados/Vuira#1]
En la ventana de auxiliar, al dar click sobre la caja de cuenta predial envía un mensaje, lo mismo sucede al teclear el primer carácter envía un mensaje y no deja continuar capturando la información (Revisar el evento on key press)

**Comment by ferVargasB** [comment]
Era en ventanilla por que auxiliar no tiene para agregar cuenta predial jeje. Hecho
