### ISSUE TITLE
Escribir un servicio(Nuevo) para la actualizacion de los numeros concecutivos

### ISSUE THREAD

**Issue by dante02d** [GAasociados/Vuira#7]

**Comment by dante02d** [comment]
en la carpeta de assets hay un archivo de texto que contiene un numero(Numero de folio) 
crear un servicio que resiva un numero y avance le numero almacenado en la cantidad equivalente al numero resivido,
Ej. Numero en el archivo de texto (3810)
numero resivido(5)
Nuevo nuemero en el arvhivo de texto (3815)

**Comment by ferVargasB** [comment]
Hecho.
El arreglo lo regreso en formato JSON.
